name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# Menambahkan izin agar bot bisa menyimpan gambar ke branch 'output'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        # TYPO SUDAH DIPERBAIKI DI SINI
        uses: actions/checkout@v4

      - name: Generate the Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: alvinskie
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy SVG to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
